In [8]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

#### I will create an array with my first name, last name, birth state and my favorite color.

In [16]:
my_array = make_array('noah', 'miller', 'tacoma', 'green')
my_array

array(['noah', 'miller', 'tacoma', 'green'], dtype='<U6')

In [15]:
my_array_capital = np.char.upper(my_array)
my_array_capital

array(['NOAH', 'MILLER', 'TACOMA', 'GREEN'], dtype='<U6')

In [21]:
np.char.count(my_array, 'a')

array([1, 0, 2, 0])

#### I will now create an array with every other odd number from 1 to 41

In [28]:
odd_number = np.arange(1,42,4)
odd_number

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

In [31]:
sum_odds = np.sum(odd_number)
sum_odds

231

In [32]:
prod_odds = np.prod(odd_number)
prod_odds

-749857315

In [27]:
natural_log = np.log(odd_number)
natural_log

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])